name: Build and Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --add-data "assets;assets" --icon=assets/TNIVO.ico src/main.py

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ github.run_number }} ./dist/main.exe --title "Release ${{ github.run_number }}" --notes "Automated release ${{ github.run_number }}" --generate-notes
